FactoryGirl.define do

  factory :apartment, class: Apartment do
    before(:create) do |apartment|
      apartment.attributes = {
        "P_NAME": "EXECUTIVE PARK APTS",
        "P_TYPE": "AB",
        "MARKET_AREA": "DK01",
        "P_STREET_NUMBER": 2580,
        "P_STREET_NAME": "BRIARCLIFF RD",
        "P_CROSS_STREET_NAME": "WOODCLIFF DR",
        "P_CITY": "ATLANTA",
        "P_ZIP": 30329,
        "COUNTY": "DEKALB",
        "DISTRICT2": "",
        "SQUARE": 1,
        "PARCEL": 1,
        "ZONING": "",
        "ZONING_PERMITTING_DATE": "",
        "UNITS_COMPLETED": 50,
        "#_ACRES": "3.86",
        "SF_LAND": "168141.6",
        "LAND_SALE_DATE": "2016-08-01",
        "LAND_SALE_PRICE": 0,
        "_ACRE": "",
        "_SF": "",
        "_UNIT_LAND": "",
        "sale_date": "2016-08-01",
        "SALE_PRICE": 6900000,
        "_UNIT_PROJECT": "",
        "TAX_OWNER": "REAL ESTATE ENTERPRISES/CHILDREN'S HEALTHCARE/CHILDREN",
        "O_STREET_NAME": "TULLIE CIR",
        "O_CITY": "ATALNTA",
        "O_PHONE": "(404) 785-7600",
        "O_REP": "DONNA HYLAND,ETAL",
        "BROKER": "UNKNOWN TO US",
        "B_PHONE": "",
        "B_STREET_NAME": "",
        "B_CITY": "",
        "B_REP": "",
        "B_REP2": "",
        "PLANNER": nil,
        "HEATED_SF": "51152",
        "MONTHLY_INCOME": "",
        "YEARLY_INCOME": "",
        "0_BED": "",
        "1_BED": 17,
        "2_BED": 23,
        "3_BED": "10",
        "4_BED": "",
        "SELLER_FORECLOSEE": "EXECUTIVE PARK APARTMENTS II/KENCO/KEN EDWARD",
        "S_STREET_NAME": "BRIARCLIFF ",
        "S_CITY": "ATLANTA",
        "S_PHONE": "(404) 633-0401",
        "ATTORNEY": "MORRIS-MAN",
        "ATTORNEY_PHONE": "(404) 233-7000",
        "_LOAN": "",
        "LENDER": "",
        "L_STREET_NAME": "",
        "L_CITY": "",
        "L_PHONE": "",
        "L_REP": "",
        "_C_LOAN": "",
        "C_LENDER": "",
        "C_L_STREET_NAME": "",
        "C_L_CITY": "",
        "C_L_PHONE": "",
        "C_L_REP": "",
        "ONSITE_PHONE": "(404) 785-7600",
        "ONSITE_MANAGER": "CHILDRENS HEALTHCARE ",
        "UTILITIES": "",
        "APPLICATION_FEE": "",
        "DEPOSIT": "",
        "REFUND": "",
        "LEASE": "",
        "_EQUITY": "6900000",
        "__EQUITY": 1,
        "_DOWNPAYMENT": "6900000",
        "__DOWNPAYMENT": 1,
        "_UNDERLYING": "",
        "_PURCHASE_NOTE": "",
        "0_MIN_SF": "",
        "1_MIN_SF": 770,
        "2_MIN_SF": "1000",
        "3_MIN_SF": "1350",
        "4_MIN_SF": "",
        "0_MAX_SF": "",
        "1_MAX_SF": 785,
        "2_MAX_SF": "1060",
        "3_MAX_SF": "1360",
        "4_MAX_SF": "",
        "0_MIN_": "",
        "1_MIN_": "",
        "2_MIN_": "",
        "3_MIN_": "",
        "4_MIN_": "",
        "0_MAX_": "",
        "1_MAX_": "",
        "2_MAX_": "",
        "3_MAX_": "",
        "4_MAX_": "",
        "0_NOTE_1": "",
        "1_NOTE_1": "",
        "2_NOTE_1": "",
        "3_NOTE_1": "",
        "4_NOTE_1": "",
        "M1": "IS THE 8/1/16 SALE(LAND SALE?),KENCO/KEN EDWARDS ENTERPRISES TO CHIL",
        "M2": "RENS HEALTHCARE OF ATLANTA;BROKER? SEEMS TO BE PART OF ASSEMBLEDGE*;",
        "M3": "50 UTS,BLT 1965; 3.86*ACS;SEEMS TO BE RELATED TO ASSEMBLEDGE*;",
        "M4": "PRICE*:$6.9MIL($138,000*/UT),CASH;NO NEW LOAN SHOWING IN DEED RECORDS.",
        "M5": "LENDER:NONE SHOWS;DDBK25708,PG596. *SEEMS TO BE PART OF ASSEMBLED",
        "M6": "THAT CHILDREN'S HEALTHCARE OF ATLANTA HAS BEEN UNDERTAKING FOR THE",
        "M7": "2 YEARS OR SO;IF SO,THIS WOULD IN ACTUALITY BE A LAND SALE;THUS,TH",
        "M8": "$6.9MIL FOR THE 3.86 ACS WOULD BE $41/LAND SF IF THIS TRULY IS TO BE",
        "M9": "A TEARDOWN OF APARTMENTS;DEKALB ASSESSORS ES",
        "M10": "PROPERTY:2",
        "0_MIN__1": "",
        "0_MAX__1": "",
        "1_MIN__1": "",
        "1_MAX__1": "",
        "2_MIN__1": "",
        "2_MAX__1": "",
        "3_MIN__1": "",
        "3_MAX__1": "",
        "4_MIN__1": "",
        "4_MAX__1": "",
        "0_MIN__2": "",
        "0_MAX__2": "",
        "1_MIN__2": "",
        "1_MAX__2": "",
        "2_MIN__2": "",
        "2_MAX__2": "",
        "3_MIN__2": "",
        "3_MAX__2": "",
        "4_MIN__2": "",
        "4_MAX__2": "",
        "0_MIN__3": "",
        "0_MAX__3": "",
        "1_MIN__3": "",
        "1_MAX__3": "",
        "2_MIN__3": "",
        "2_MAX__3": "",
        "3_MIN__3": "",
        "3_MAX__3": "",
        "4_MIN__3": "",
        "4_MAX__3": "",
        "0_MIN__4": "",
        "0_MAX__4": "",
        "1_MIN__4": "",
        "1_MAX__4": "",
        "2_MIN__4": "",
        "2_MAX__4": "",
        "3_MIN__4": "",
        "3_MAX__4": "",
        "4_MIN__4": "",
        "4_MAX__4": "",
        "0_INCREASE": "",
        "1_INCREASE": nil,
        "2_INCREASE": nil,
        "3_INCREASE": "",
        "4_INCREASE": "",
        "OCCUPANCY": "",
        "GOVERNMENT_PROGRAM": "",
        "INSIDER_DESCRIPTION": "APARTMENT SALE",
        "AKA": "",
        "SURVEY": "",
        "PERMITTED": nil,
        "PREVIOUS_INSIDER_DATE_1": "",
        "insider_date": "2016-09-02",
        "P_STATE": "GA",
        "PREVIOUS_INSIDER_DATE_2": "",
        "PREVIOUS_INSIDER_DATE_3": "",
        "O_REP2": "LESLIE JONES,RUTH FOWLER,REX ADAMS,ETAL",
        "O_STREET_NUMBER": 1600,
        "O_SUITE_NUMBER": "ADMINIS",
        "O_STATE": "GA",
        "O_ZIP": 30329,
        "B_STREET_NUMBER": nil,
        "B_P_O_BOX_NUMBER": "",
        "B_SUITE_NUMBER": "",
        "B_STATE": "",
        "B_ZIP": nil,
        "S_REP": "CLAYTON EDWARDS JR;KEN EDWARDS;CLAY EDWARDS",
        "S_STREET_NUMBER": 2219,
        "S_P_O_BOX_NUMBER": "",
        "S_SUITE_NUMBER": "",
        "S_STATE": "GA",
        "S_ZIP": 30329,
        "L_STREET_NUMBER": nil,
        "L_SUITE_NUMBER": "",
        "L_STATE": "",
        "L_ZIP": nil,
        "C_L_STREET_NUMBER": nil,
        "C_L_P_O_BOX_NUMBER": "",
        "C_L_STATE": "",
        "C_L_ZIP": nil,
        "C_L_SUITE_NUMBER": "",
        "UNBUILT_PHASE_2_UNITS": "",
        "PHASE_3_UNITS": "",
        "PHASE_4_UNITS": "",
        "START_DATE": "",
        "CONCESSIONS": "",
        "6TH_HALF_YEAR": "",
        "THIS_HALF_YEAR": "",
        "2ND_HALF_YEAR": "",
        "3RD_HALF_YEAR": "",
        "3_YRS_FROM_NOW_\u0026_BEYOND": "",
        "DISTRICT": 18,
        "LANDLOT": 157,
        "LANDLOT2": "",
        "0_avg_": "",
        "1_avg_": nil,
        "2_avg_": nil,
        "3_avg_": "",
        "4_avg_": "",
        "DESCRIPTION": "APARTMENT SALE",
        "2_avg__per_sf": nil,
        "SECTION": "",
        "O_P_O_BOX_NUMBER": "",
        "O_PHONE2_FAX": "(404)785-5589;570-9717",
        "PARCEL2": "",
        "LEASING_PHONE": "(404) 633-0401",
        "SQUARE2": "",
        "LEASING_REP": "CLAY EDWARDS,ETAL",
        "LEASING_REP2": "",
        "LEASING_STREET_NUMBER": 2219,
        "LEASING_STREET_NAME": "BRIARCLIF",
        "LEASING_P_O_BOX_NUMBER": "",
        "LEASING_SUITE_NUMBER": "OFFICE",
        "LEASING_CITY": "ATLANTA",
        "LEASING_STATE": "GA",
        "LEASING_ZIP": 30329,
        "L_P_O_BOX_NUMBER": "",
        "OWNER2_ATTENTION": "DONNA HYLAND,ETAL",
        "LOAN_START_DATE": "",
        "LOAN_DUE_DATE": "",
        "C_LOAN_START_DATE": "",
        "C_LOAN_DUE_DATE": "",
        "OWNER_OCCUPANCY": "",
        "PET_DEPOSIT": "",
        "4TH_HALF_YEAR": "",
        "5TH_HALF_YEAR": "",
        "OWNER": "CHILDRENS HEALTHCARE/CHILDREN'S HEALTHCARE O",
        "LEASING_COMPANY": "KENCO/KEN E",
        "UNITS_PER_ACRE": nil,
        "UNITS_VACANT": "",
        "built_complete": "1965-12-31",
        "ORIGINALLY_BUILT": "",
        "_LOAN2": "",
        "LOAN2_START_DATE": "",
        "LOAN2_DUE_DATE": "",
        "FORECLOSURE_PRICE": "",
        "LENDER2": "",
        "CLASSIFICATION": "",
        "FORECLOSURE_DATE": ""
      }
    end
  end

  factory :apartment2, class: Apartment do
    before(:create) do |apartment|
      apartment.attributes = {
        "id": 245,
        "P_NAME": "BELARA/WAS MARQUIS OF NORTH DRUID HILLS/WAS PRESERVE/MARQUIS N.DRUID/PRESERVE@BRIARCLIFF/POST OAK/THE PRESERVE AT BRIARCLIFF/MARQUIS OF NORTH DRUID HILLS/MARQUISE",
        "P_TYPE": "AB",
        "MARKET_AREA": "DK01",
        "P_STREET_NUMBER": 1570,
        "P_STREET_NAME": "SHERIDAN RD;BRIARCLIFF RD",
        "P_CROSS_STREET_NAME": "BRIARCLIFF RD",
        "P_CITY": "ATLANTA",
        "P_ZIP": 30329,
        "COUNTY": "DEKALB",
        "DISTRICT2": "",
        "SQUARE": 1,
        "PARCEL": 1,
        "ZONING": "6/15/90",
        "ZONING_PERMITTING_DATE": "",
        "UNITS_COMPLETED": 182,
        "#_ACRES": "7.33",
        "SF_LAND": "319294.8",
        "LAND_SALE_DATE": "1992-09-23",
        "LAND_SALE_PRICE": 1950000,
        "_ACRE": "266030.01",
        "_SF": "6.1",
        "_UNIT_LAND": "10720",
        "sale_date": "2016-05-31",
        "SALE_PRICE": 29575000,
        "_UNIT_PROJECT": "",
        "TAX_OWNER": "BELARA APARTMENTS/M.BANKS REALTY PARTNERS/MBANKS",
        "O_STREET_NAME": "LAKE HEARN DR",
        "O_CITY": "ATLANTA",
        "O_PHONE": "(404) 574-8544",
        "O_REP": "MARVIN BANKS,ETAL",
        "BROKER": "CB RICHARD ELLIS/CBRE",
        "B_PHONE": "(404) 504-7900",
        "B_STREET_NAME": "PEACHTREE RD",
        "B_CITY": "ATLANTA",
        "B_REP": "PAUL BERRY,ETAL",
        "B_REP2": "SHEA CAMPBELL,KEVIN GEIG",
        "PLANNER": nil,
        "HEATED_SF": "170115",
        "MONTHLY_INCOME": "",
        "YEARLY_INCOME": "",
        "0_BED": "",
        "1_BED": 68,
        "2_BED": 102,
        "3_BED": "12",
        "4_BED": "",
        "SELLER_FORECLOSEE": "CWS DRUID HILLS/CWS CAPITAL PARTNERS/CWSFG",
        "S_STREET_NAME": "CORPORATE P",
        "S_CITY": "NEWPORT",
        "S_PHONE": "(949)640-4200;(800)466-0020",
        "ATTORNEY": "UNKNOWN TO",
        "ATTORNEY_PHONE": "(770) 438-8000",
        "_LOAN": "20000000",
        "LENDER": "FREDDIE MAC/GRANDBRIDGE/FEDERA",
        "L_STREET_NAME": "JONES BR",
        "L_CITY": "MCLEAN",
        "L_PHONE": "(703)714-2849;",
        "L_REP": "DAVID GOOZMAN;GRANDBRIDGE;ALAN TAPIE(GRAND",
        "_C_LOAN": "",
        "C_LENDER": "GRANDBRIDGE REAL ESTATE CA",
        "C_L_STREET_NAME": "17TH ST NW",
        "C_L_CITY": "ATLANT",
        "C_L_PHONE": "(404)602-1389;",
        "C_L_REP": "ALAN TAPIE,TOM",
        "ONSITE_PHONE": "(404)634-4599;",
        "ONSITE_MANAGER": "FIRST COMMUNITIES",
        "UTILITIES": "",
        "APPLICATION_FEE": "",
        "DEPOSIT": "",
        "REFUND": "",
        "LEASE": "",
        "_EQUITY": "12700000",
        "__EQUITY": 0,
        "_DOWNPAYMENT": "12700000",
        "__DOWNPAYMENT": 0,
        "_UNDERLYING": "",
        "_PURCHASE_NOTE": "",
        "0_MIN_SF": "",
        "1_MIN_SF": 550,
        "2_MIN_SF": "966",
        "3_MIN_SF": "1420",
        "4_MIN_SF": "",
        "0_MAX_SF": "",
        "1_MAX_SF": 762,
        "2_MAX_SF": "1201",
        "3_MAX_SF": "1420",
        "4_MAX_SF": "",
        "0_MIN_": "",
        "1_MIN_": "974",
        "2_MIN_": "1586",
        "3_MIN_": "1758",
        "4_MIN_": "",
        "0_MAX_": "",
        "1_MAX_": "1014",
        "2_MAX_": "1586",
        "3_MAX_": "1758",
        "4_MAX_": "",
        "0_NOTE_1": "12-1/BED 7",
        "1_NOTE_1": "28-1/BED 762SF;12-2/BED 966SF;",
        "2_NOTE_1": "40-2/BED 1201SF;50-2/BED 1118SF",
        "3_NOTE_1": "12-3/BED 1",
        "4_NOTE_1": "",
        "M1": "CBRE(PAUL BERRY,SHEA CAMPBELL,MALCOLM MCCOMB,KEVIN GEIGER)BROKERED",
        "M2": "5/31/2016 SALE,CWS CAPITAL TO SAGE EQUITIES/M.BANKS REALTY PARTNERS;",
        "M3": "182 UTS,BLT 1992-93; 7.33 ACS;NO INFO:OCCUP:95%;NO INFO;CAP,NOI,EXPENS",
        "M4": "PRICE:$29.6MIL($162,500/UT);$9.6MIL EQ+NEW LN:$20MIL,5/31/16,DUE ?",
        "M5": "LENDER;FREDDIE MAC/GRANDBRIDGE;DBK25586,PG429;HAD SOLD 2/21/13($2",
        "M6": "($123,626/UT);EQUITY RESIDN BOUGHT IT 3/22/07 FROM POST($24MIL($13",
        "M7": "UNIT);DEKALB ASSESSORS ESTIM 2015 VALUE:$17.063MIL($93,753/UT). TH",
        "M8": "HAS CHANGED ITS NAME FROM MARQUIS OF NORTH DRUID HILLS TO BALARA AS ",
        "M9": "JUNE 2016; POST HAD BUILT THIS IN 1992-93.",
        "M10": "",
        "0_MIN__1": "",
        "0_MAX__1": "",
        "1_MIN__1": "",
        "1_MAX__1": "",
        "2_MIN__1": "",
        "2_MAX__1": "",
        "3_MIN__1": "",
        "3_MAX__1": "",
        "4_MIN__1": "",
        "4_MAX__1": "",
        "0_MIN__2": "",
        "0_MAX__2": "",
        "1_MIN__2": "",
        "1_MAX__2": "",
        "2_MIN__2": "",
        "2_MAX__2": "",
        "3_MIN__2": "",
        "3_MAX__2": "",
        "4_MIN__2": "",
        "4_MAX__2": "",
        "0_MIN__3": "",
        "0_MAX__3": "",
        "1_MIN__3": "",
        "1_MAX__3": "",
        "2_MIN__3": "",
        "2_MAX__3": "",
        "3_MIN__3": "",
        "3_MAX__3": "",
        "4_MIN__3": "",
        "4_MAX__3": "",
        "0_MIN__4": "",
        "0_MAX__4": "",
        "1_MIN__4": "",
        "1_MAX__4": "",
        "2_MIN__4": "",
        "2_MAX__4": "",
        "3_MIN__4": "",
        "3_MAX__4": "",
        "4_MIN__4": "",
        "4_MAX__4": "",
        "0_INCREASE": "",
        "1_INCREASE": nil,
        "2_INCREASE": nil,
        "3_INCREASE": "",
        "4_INCREASE": "",
        "OCCUPANCY": "",
        "GOVERNMENT_PROGRAM": "",
        "INSIDER_DESCRIPTION": "APARTMENT SALE",
        "AKA": "WAS POST OAK/NOW THE PRESERVE@BRIAR",
        "SURVEY": "SURVEY",
        "PERMITTED": 1822,
        "PREVIOUS_INSIDER_DATE_1": "3/8/13",
        "insider_date": "2016-06-03",
        "P_STATE": "GA",
        "PREVIOUS_INSIDER_DATE_2": "3/23/07",
        "PREVIOUS_INSIDER_DATE_3": "4/7/93",
        "O_REP2": "UZI ZIV,ETAL",
        "O_STREET_NUMBER": 1200,
        "O_SUITE_NUMBER": "#200",
        "O_STATE": "GA",
        "O_ZIP": 30319,
        "B_STREET_NUMBER": 3280,
        "B_P_O_BOX_NUMBER": "",
        "B_SUITE_NUMBER": "#140",
        "B_STATE": "GA",
        "B_ZIP": 30305,
        "S_REP": "MARY ELLEN BARLOW,MIKE ENGELS;STEVE SHERWOOD;BILL WILLIAMS,ETAL",
        "S_STREET_NUMBER": 14,
        "S_P_O_BOX_NUMBER": "",
        "S_SUITE_NUMBER": "#210",
        "S_STATE": "CA",
        "S_ZIP": 92660,
        "L_STREET_NUMBER": 8200,
        "L_SUITE_NUMBER": "MS 202",
        "L_STATE": "VA",
        "L_ZIP": 22102,
        "C_L_STREET_NUMBER": 271,
        "C_L_P_O_BOX_NUMBER": "",
        "C_L_STATE": "GA",
        "C_L_ZIP": 30363,
        "C_L_SUITE_NUMBER": "#750",
        "UNBUILT_PHASE_2_UNITS": "",
        "PHASE_3_UNITS": "",
        "PHASE_4_UNITS": "",
        "START_DATE": "1/15/93",
        "CONCESSIONS": "",
        "6TH_HALF_YEAR": "",
        "THIS_HALF_YEAR": "",
        "2ND_HALF_YEAR": "",
        "3RD_HALF_YEAR": "",
        "3_YRS_FROM_NOW_\u0026_BEYOND": "",
        "DISTRICT": 18,
        "LANDLOT": 153,
        "LANDLOT2": "154",
        "0_avg_": "",
        "1_avg_": 994,
        "2_avg_": "1586.0",
        "3_avg_": "1758",
        "4_avg_": "",
        "DESCRIPTION": "APARTMENT SALE",
        "2_avg__per_sf": "1.463774804",
        "SECTION": "",
        "O_P_O_BOX_NUMBER": "",
        "O_PHONE2_FAX": "(404)252-8900;574-8544",
        "PARCEL2": "",
        "LEASING_PHONE": "(404)252-8900;",
        "SQUARE2": "",
        "LEASING_REP": "GINA DOWDY,ETAL",
        "LEASING_REP2": "PEGGY WASKOM,ED ROMANO,KANDY COLEMAN,BRANDY B",
        "LEASING_STREET_NUMBER": 1200,
        "LEASING_STREET_NAME": "LAKE HEAR",
        "LEASING_P_O_BOX_NUMBER": "",
        "LEASING_SUITE_NUMBER": "#200",
        "LEASING_CITY": "ATLANTA",
        "LEASING_STATE": "GA",
        "LEASING_ZIP": 30319,
        "L_P_O_BOX_NUMBER": "",
        "OWNER2_ATTENTION": "MARVIN BANKS,ETAL",
        "LOAN_START_DATE": "5/31/16",
        "LOAN_DUE_DATE": "",
        "C_LOAN_START_DATE": "5/31/16",
        "C_LOAN_DUE_DATE": "",
        "OWNER_OCCUPANCY": "",
        "PET_DEPOSIT": "",
        "4TH_HALF_YEAR": "",
        "5TH_HALF_YEAR": "",
        "OWNER": "M.BANKS REALTY PRNRS/SAGE EQUITIES/M.BANKS R",
        "LEASING_COMPANY": "FIRST COMMU",
        "UNITS_PER_ACRE": nil,
        "UNITS_VACANT": "",
        "built_complete": "1993-12-15",
        "ORIGINALLY_BUILT": "12/31/94",
        "_LOAN2": "",
        "LOAN2_START_DATE": "",
        "LOAN2_DUE_DATE": "",
        "FORECLOSURE_PRICE": "",
        "LENDER2": "",
        "CLASSIFICATION": "CLASS A",
        "FORECLOSURE_DATE": ""
      }
    end
  end

end
