FactoryGirl.define do

  factory :franchise, class: Franchise do
    before(:create) do |franchise|
      franchise.attributes = {
        "id": 761,
        "P_NAME": "WALGREEN'S",
        "PROJECT_TYPE": "F",
        "P_STREET_NUMBER": "2304",
        "P_STREET_NAME": "BRIARCLIFF RD",
        "P_CROSS_STREET_NAME": "NORTH DRUID HILLS RD",
        "P_CITY": "ATLANTA",
        "P_ZIP": "30322",
        "COUNTY": "DEKALB",
        "DISTRICT2": "",
        "SQUARE": "6",
        "PARCEL": "1",
        "DEPTH": "",
        "WIDTH": "",
        "SF_LAND": "",
        "land_sale_date": '2017-01-01',
        "LAND_SALE_PRICE": "",
        "PRICE_PER_ACRE": "",
        "PRICE_PER_SF_LAND": "",
        "sale_date": "2008-08-26",
        "SALE_PRICE": "3825000.00",
        "PRICE_PER_SF_BUILDING": "255",
        "TAX_OWNER": "PARADISE DEV/MTW MOUNT VERNON WOODS",
        "O_STREET_NAME": "RIGBY LN",
        "O_CITY": "SAFETY HARBOR",
        "O_PHONE": "(727) 726-1115",
        "O_REP": "DAVID A. BALDWIN",
        "BUILDER": "",
        "B_PHONE": "",
        "B_STREET_NAME": "",
        "B_CITY": "",
        "ARCHITECT": "",
        "PLANNER": "",
        "PREVIOUS_INSIDER_DATE_1": "",
        "PREVIOUS_INSIDER_DATE_2": "",
        "PREVIOUS_INSIDER_DATE_3": "",
        "IMPROVED": "",
        "LEGNTH": "",
        "SELLER": "DINOS, JOHN/NORTH DRUID DEV",
        "S_STREET_NAME": "WEST WIEUCA RD",
        "S_CITY": "ATLANTA",
        "S_STATE": "GA",
        "BROKER": "UNKNOWN TO US",
        "BROKER_PHONE": "",
        "PERMANENT_LOAN": "",
        "LENDER": "",
        "L_STREET_NUMBER": "",
        "L_CITY": "",
        "L_PHONE": "",
        "CONSTRUCTION_LOAN": "6940000",
        "C_LENDER": "BANK OF AMERICA",
        "C_L_STREET_NUMBER": "600",
        "C_L_CITY": "ATLANTA",
        "C_L_PHONE": "(404) 529-4132",
        "C_L_REP": "COMM RE DEPT",
        "LEASING_REP": "",
        "EQUITY": "3825000",
        "PERCENTAGE_EQUITY": "",
        "DOWNPAYMENT": "3825000",
        "PERCENTAGE_DOWNPAYMENT": "",
        "UNDERLYING": "",
        "PURCHASE_NOTE": "",
        "ASKING_PRICE": "",
        "DESCRIPTION": "SMALL RETAIL SALE-PHARMACY",
        "AKA": "",
        "SURVEY": "",
        "FRONT": "",
        "INSIDER_SORT": "1",
        "insider_date": "2008-09-12",
        "LEASING_PHONE": "",
        "O_STREET_NUMBER": "2901",
        "O_STATE": "FL",
        "O_ZIP": "34695",
        "LEASING_STREET_NUMBER": "",
        "LEASING_STREET_NAME": "",
        "LEASING_CITY": "",
        "LEASING_ZIP": "",
        "LEASING_SUITE_NUMBER": "",
        "O_SUITE_NUMBER": "",
        "LEASING_STATE": "",
        "P_STATE": "GA",
        "OCCUPIED": "",
        "VACANT": "",
        "LOW_RENT": "",
        "START": "",
        "LEASED_PREVIOUS_90_DAYS": "",
        "M1": "THIS IS THE 8/26/2008 SALE: JOHN DINOS TO DAVID",
        "M2": "A. BALDWIN. WE ARE UNAWARE OF ANY BROKER ASSIST.",
        "M3": "IS 1.11 ACS, TO BLD APPX 15,000 SF, TO OPEN APRIL 09.",
        "M4": "SALE PRICE: $3,825,000, ($255/SF). LN:$6,940,000 @1YR.",
        "M5": "LENDER: BANK OF AMERICA. DEEDBK21021, P203. THERE",
        "HIGH_RENT": "",
        "LEASING_P_O_BOX_NUMBER": "",
        "O_P_O_BOX_NUMBER": "",
        "M6": "IS PRESENTLY A BURGER KING AT THIS LOCATION. IT WILL",
        "M7": "BE DEMOLISHED AND REPLACED WITH A WALGREEN'S PHARMACY.",
        "1ST_95": "",
        "AFTER_3_YEARS": "",
        "MARKET_AREA": "9",
        "LEASING_REP2": "",
        "O_REP2": "MICHAEL T. WAGNER",
        "ANCHOR1": "WALGREEN'S",
        "ANCHOR2": "",
        "B_STREET_NUMBER": "",
        "B_P_O_BOX_NUMBER": "",
        "B_REP2": "",
        "B_REP": "",
        "S_STREET_NUMBER": "175",
        "S_P_O_BOX_NUMBER": "",
        "S_ZIP": "30342",
        "S_PHONE": "(404) 256-9456",
        "S_REP2": "",
        "L_REP": "",
        "L_REP2": "",
        "L_P_O_BOX_NUMBER": "",
        "L_STREET_NAME": "",
        "L_STATE": "",
        "L_ZIP": "",
        "C_L_REP2": "",
        "C_L_STREET_NAME": "PEACHTREE ST",
        "C_L_P_O_BOX_NUMBER": "",
        "C_L_STATE": "GA",
        "C_L_ZIP": "30308",
        "S_REP": "JOHN DINOS",
        "S_SUITE_NUMBER": "STE 201",
        "B_SUITE_NUMBER": "",
        "B_STATE": "",
        "B_ZIP": "",
        "L_SUITE_NUMBER": "",
        "#_ACRES": 1,
        "#_SQ_FT_BUILT": 15000,
        "PREVIOUS_OCCUPIED": "",
        "PREVIOUS_VACANT": "",
        "UNBUILT_PHASE_2_SF": "",
        "PHASE_3_SF": "",
        "DISTRICT": "18",
        "LANDLOT2": "",
        "PARCEL2": "",
        "PREVIOUS_SQ_FT_BUILT": "",
        "SECTION": "",
        "2ND_OWNER_PHONE": "",
        "LEASING_PHONE2_FAX": "",
        "LANDLOT": "153",
        "CLASSIFICATION": "",
        "C_L_SUITE_NUMBER": "6TH FL",
        "#_OF_BUILDINGS": "",
        "2ND_OWNER": "",
        "CLASSIFICATION2": "",
        "CLASSIFICATION3": "",
        "LOAN_PER_SQ_FT": "",
        "C_LOAN_PER_SQ_FT": "462.6666667",
        "2ND_95": "",
        "OCCTEST": "",
        "FORECLOSURE_DATE": '2017-01-01',
        "ASSUMED_LOAN": "",
        "O_PHONE2_FAX": "",
        "M8": "",
        "M9": "",
        "M10": "",
        "1ST_96": "",
        "PHASE_4_SF": "",
        "MEDIAN_RENTAL_RATE": "",
        "LEASE_TERMS": "",
        "LOAN_START_DATE": "",
        "LOAN_COMPLETE_DATE": "",
        "LOAN_TERMS": "",
        "C_LOAN_START_DATE": "8/26/08",
        "C_LOAN_COMPLETE_DATE": "8/26/09",
        "C_LOAN_TERMS": "1",
        "OWNER": "PARADISE DEVELOPMENT",
        "LEASING_COMPANY": "",
        "LEASE_TERMS_ALLOWANCE": "",
        "2ND_OWNER_REP": "",
        "2ND_OWNER_REP2": "",
        "2ND_OWNER_STREET_NUMBER": "",
        "2ND_OWNER_P_O_BOX_NUMBER": "",
        "2ND_OWNER_STREET_NAME": "",
        "2ND_OWNER_SUITE_NUMBER": "",
        "2ND_OWNER_CITY": "",
        "2ND_OWNER_STATE": "",
        "2ND_OWNER_ZIP": "",
        "2ND_OWNER_PHONE2_FAX": "",
        "PERCENTAGE_OCCUPANCY": "",
        "PERCENTAGE_VACANCY": "",
        "MANAGEMENT_COMPANY": "",
        "MANAGEMENT_REP": "",
        "MANAGEMENT_REP2": "",
        "MANAGEMENT_STREET_NUMBER": "",
        "MANAGEMENT_P_O_BOX_NUMBER": "",
        "MANAGEMENT_STREET_NAME": "",
        "MANAGEMENT_SUITE_NUMBER": "",
        "MANAGEMENT_CITY": "",
        "MANAGEMENT_STATE": "",
        "MANAGEMENT_ZIP": "",
        "MANAGEMENT_PHONE": "",
        "MANAGEMENT_PHONE2_FAX": "",
        "ATTENTION": "DAVID A. BALDWIN",
        "built_complete": "2009-04-15",
        "ORIGINALLY_BUILT": "",
        "ATTENTION2": "",
        "S_PHONE2_FAX": "",
        "B_PHONE2_FAX": "",
        "L_PHONE2_FAX": "",
        "C_L_PHONE2_FAX": "",
        "2ND_96": "",
        "UNITS": "",
        "RESULTS": "",
        "INSIDER_DESCRIPTION": "SMALL RETAIL SALE-PHARMACY",
        "PURCHASE_NOTE_START_DATE": "",
        "PURCHASE_NOTE_DUE_DATE": "",
        "CAP_RATE": "",
        "GROSS_NET": "",
        "1ST_97": "",
        "FLOORS": "",
        "2ND_97": "",
        "FORECLOSED_PRICE": "",
        "ATTORNEY": "",
        "ATTORNEY_PHONE": "",
        "EXISTING_PERMANENT_LOAN": "",
        "EXISTING_CONSTRUCITON_LOAN": "",
        "PRICE_PER_UNIT": ""
      }
    end
  end

  factory :franchise2, class: Franchise do
    before(:create) do |franchise|
      franchise.attributes = {
        "id": 1001,
        "P_NAME": "BRIARCLIFF RD#2566",
        "PROJECT_TYPE": "F",
        "P_STREET_NUMBER": "2566",
        "P_STREET_NAME": "BRIARCLIFF RD",
        "P_CROSS_STREET_NAME": "NORTH DRUID HILLS RD",
        "P_CITY": "ATLANTA",
        "P_ZIP": "30329",
        "COUNTY": "DEKALB",
        "DISTRICT2": "",
        "SQUARE": "6",
        "PARCEL": "4",
        "DEPTH": "",
        "WIDTH": "",
        "SF_LAND": "",
        "land_sale_date": '2017-01-01',
        "LAND_SALE_PRICE": "",
        "PRICE_PER_ACRE": "",
        "PRICE_PER_SF_LAND": "",
        "sale_date": "2014-06-24",
        "SALE_PRICE": "2450000.00",
        "PRICE_PER_SF_BUILDING": "90.673575",
        "TAX_OWNER": "LAASE, ED R./BRIARCLIFF ASSI=OCIATES",
        "O_STREET_NAME": "VENEZIA",
        "O_CITY": "NEWPORT COAST",
        "O_PHONE": "(949) 494-6448",
        "O_REP": "ED R. LAASE",
        "BUILDER": "",
        "B_PHONE": "",
        "B_STREET_NAME": "",
        "B_CITY": "",
        "ARCHITECT": "",
        "PLANNER": "",
        "PREVIOUS_INSIDER_DATE_1": "",
        "PREVIOUS_INSIDER_DATE_2": "",
        "PREVIOUS_INSIDER_DATE_3": "",
        "IMPROVED": "",
        "LEGNTH": "",
        "SELLER": "O'NEILL, DAN/COLUMBIA DRUID HILLS",
        "S_STREET_NAME": "TERRELL MILL RD",
        "S_CITY": "MARIETTA",
        "S_STATE": "GA",
        "BROKER": "UNKNOWN TO US",
        "BROKER_PHONE": "",
        "PERMANENT_LOAN": "",
        "LENDER": "",
        "L_STREET_NUMBER": "",
        "L_CITY": "",
        "L_PHONE": "",
        "CONSTRUCTION_LOAN": "",
        "C_LENDER": "",
        "C_L_STREET_NUMBER": "",
        "C_L_CITY": "",
        "C_L_PHONE": "",
        "C_L_REP": "",
        "LEASING_REP": "",
        "EQUITY": "2450000",
        "PERCENTAGE_EQUITY": "",
        "DOWNPAYMENT": "2450000",
        "PERCENTAGE_DOWNPAYMENT": "",
        "UNDERLYING": "",
        "PURCHASE_NOTE": "",
        "ASKING_PRICE": "",
        "DESCRIPTION": "SMALL RETAIL SALE-STRIP SHPPING",
        "AKA": "",
        "SURVEY": "",
        "FRONT": "",
        "INSIDER_SORT": "1",
        "insider_date": "2014-06-27",
        "LEASING_PHONE": "",
        "O_STREET_NUMBER": "1",
        "O_STATE": "CA",
        "O_ZIP": "92657",
        "LEASING_STREET_NUMBER": "",
        "LEASING_STREET_NAME": "",
        "LEASING_CITY": "",
        "LEASING_ZIP": "",
        "LEASING_SUITE_NUMBER": "",
        "O_SUITE_NUMBER": "",
        "LEASING_STATE": "",
        "P_STATE": "GA",
        "OCCUPIED": "",
        "VACANT": "",
        "LOW_RENT": "",
        "START": "",
        "LEASED_PREVIOUS_90_DAYS": "",
        "M1": "DAN O'NEILL SOLD27,020 SF TO ED R. LAASE ON 6/24/14.",
        "M2": "WE ARE UNAWARE OF ANY BROKER INVOLVEMENT IN THIS DEAL.",
        "M3": "THIS IS 27,020 SQ FT, BUILT IN 2013, ON APPROX 2.9 ACS.",
        "M4": "SALE PRICE: $2,450,000, ($91/SQ FT). CASH. NO LN SHWING.",
        "M5": "LENDER: NONE. DEEDBK24443, P253. THIS IS A SMALL STRIP",
        "HIGH_RENT": "",
        "LEASING_P_O_BOX_NUMBER": "",
        "O_P_O_BOX_NUMBER": "",
        "M6": "SHOPPING CTR. SOME OF THE TENANTS INCLUDE: MATTRESS FIRM,",
        "M7": "NERKS CAFE AND SPRING.",
        "1ST_95": "",
        "AFTER_3_YEARS": "",
        "MARKET_AREA": "",
        "LEASING_REP2": "",
        "O_REP2": "",
        "ANCHOR1": "MATTRESS FIRM",
        "ANCHOR2": "NERKS CAFE",
        "B_STREET_NUMBER": "",
        "B_P_O_BOX_NUMBER": "",
        "B_REP2": "",
        "B_REP": "",
        "S_STREET_NUMBER": "1355",
        "S_P_O_BOX_NUMBER": "",
        "S_ZIP": "30067",
        "S_PHONE": "(678) 460-3122",
        "S_REP2": "",
        "L_REP": "",
        "L_REP2": "",
        "L_P_O_BOX_NUMBER": "",
        "L_STREET_NAME": "",
        "L_STATE": "",
        "L_ZIP": "",
        "C_L_REP2": "",
        "C_L_STREET_NAME": "",
        "C_L_P_O_BOX_NUMBER": "",
        "C_L_STATE": "",
        "C_L_ZIP": "",
        "S_REP": "DAN O'NEILL",
        "S_SUITE_NUMBER": "BLDG 1478, STE 200",
        "B_SUITE_NUMBER": "",
        "B_STATE": "",
        "B_ZIP": "",
        "L_SUITE_NUMBER": "",
        "#_ACRES": 3,
        "#_SQ_FT_BUILT": 27020,
        "PREVIOUS_OCCUPIED": "",
        "PREVIOUS_VACANT": "",
        "UNBUILT_PHASE_2_SF": "",
        "PHASE_3_SF": "",
        "DISTRICT": "18",
        "LANDLOT2": "",
        "PARCEL2": "",
        "PREVIOUS_SQ_FT_BUILT": "",
        "SECTION": "",
        "2ND_OWNER_PHONE": "",
        "LEASING_PHONE2_FAX": "",
        "LANDLOT": "153",
        "CLASSIFICATION": "",
        "C_L_SUITE_NUMBER": "",
        "#_OF_BUILDINGS": "",
        "2ND_OWNER": "",
        "CLASSIFICATION2": "",
        "CLASSIFICATION3": "",
        "LOAN_PER_SQ_FT": "",
        "C_LOAN_PER_SQ_FT": "",
        "2ND_95": "",
        "OCCTEST": "",
        "FORECLOSURE_DATE": '2017-01-01',
        "ASSUMED_LOAN": "",
        "O_PHONE2_FAX": "",
        "M8": "",
        "M9": "",
        "M10": "",
        "1ST_96": "",
        "PHASE_4_SF": "",
        "MEDIAN_RENTAL_RATE": "",
        "LEASE_TERMS": "",
        "LOAN_START_DATE": "",
        "LOAN_COMPLETE_DATE": "",
        "LOAN_TERMS": "",
        "C_LOAN_START_DATE": "",
        "C_LOAN_COMPLETE_DATE": "",
        "C_LOAN_TERMS": "",
        "OWNER": "LAASE, ED R.",
        "LEASING_COMPANY": "",
        "LEASE_TERMS_ALLOWANCE": "",
        "2ND_OWNER_REP": "",
        "2ND_OWNER_REP2": "",
        "2ND_OWNER_STREET_NUMBER": "",
        "2ND_OWNER_P_O_BOX_NUMBER": "",
        "2ND_OWNER_STREET_NAME": "",
        "2ND_OWNER_SUITE_NUMBER": "",
        "2ND_OWNER_CITY": "",
        "2ND_OWNER_STATE": "",
        "2ND_OWNER_ZIP": "",
        "2ND_OWNER_PHONE2_FAX": "",
        "PERCENTAGE_OCCUPANCY": "",
        "PERCENTAGE_VACANCY": "",
        "MANAGEMENT_COMPANY": "",
        "MANAGEMENT_REP": "",
        "MANAGEMENT_REP2": "",
        "MANAGEMENT_STREET_NUMBER": "",
        "MANAGEMENT_P_O_BOX_NUMBER": "",
        "MANAGEMENT_STREET_NAME": "",
        "MANAGEMENT_SUITE_NUMBER": "",
        "MANAGEMENT_CITY": "",
        "MANAGEMENT_STATE": "",
        "MANAGEMENT_ZIP": "",
        "MANAGEMENT_PHONE": "",
        "MANAGEMENT_PHONE2_FAX": "",
        "ATTENTION": "ED R. LAASE",
        "built_complete": "2013-06-15",
        "ORIGINALLY_BUILT": "",
        "ATTENTION2": "",
        "S_PHONE2_FAX": "",
        "B_PHONE2_FAX": "",
        "L_PHONE2_FAX": "",
        "C_L_PHONE2_FAX": "",
        "2ND_96": "",
        "UNITS": "",
        "RESULTS": "",
        "INSIDER_DESCRIPTION": "SMALL RETAIL SALE-SMALL STRIP SHPPING CTR",
        "PURCHASE_NOTE_START_DATE": "",
        "PURCHASE_NOTE_DUE_DATE": "",
        "CAP_RATE": "",
        "GROSS_NET": "",
        "1ST_97": "",
        "FLOORS": "",
        "2ND_97": "",
        "FORECLOSED_PRICE": "",
        "ATTORNEY": "",
        "ATTORNEY_PHONE": "",
        "EXISTING_PERMANENT_LOAN": "",
        "EXISTING_CONSTRUCITON_LOAN": "",
        "PRICE_PER_UNIT": ""
      }
    end
  end

end
