FactoryGirl.define do

  factory :industrial, class: Industrial do
    before(:create) do |industrial|
      industrial.attributes = {
        "id": 1,
        "P_NAME": "1DUQUESNE DR#6170/ 6170 DUQUESNE DR",
        "PROJECT_TYPE": "I",
        "P_STREET_NUMBER": "6",
        "P_STREET_NAME": "DUQUESNE DR",
        "P_CROSS_STREET_NAME": "LAGRANGE BLV/FULTON INDUS",
        "P_CITY": "ATLANTA",
        "P_ZIP": "30336",
        "COUNTY": "FULTON (SOUTH)",
        "DISTRICT2": "",
        "SQUARE": "MA",
        "PARCEL": "046-0",
        "ZONING": "",
        "ZONING_PERMITTING_DATE": "",
        "SF_LAND": nil,
        "land_sale_date": '2017-01-01',
        "LAND_SALE_PRICE": 0,
        "PRICE_PER_ACRE": "",
        "PRICE_PER_SF_LAND": "",
        "sale_date": "2016-09-16",
        "SALE_PRICE": 2677065,
        "PRICE_PER_SF_BUILDING": "25.4958571",
        "TAX_OWNER": "RIFO LLC/BONDED INDUSTRIAL PROPS",
        "O_STREET_NAME": "PURDUE DR",
        "O_CITY": "ATLANTA",
        "O_PHONE": "(404) 349-6685",
        "O_REP": "DRURY GHEGA",
        "BUILDER": "",
        "B_PHONE": "",
        "B_STREET_NAME": "PEACHTREE ",
        "B_CITY": "ATLANTA",
        "ARCHITECT": "",
        "PLANNER": "",
        "PREVIOUS_INSIDER_DATE_1": "",
        "PREVIOUS_INSIDER_DATE_2": "",
        "PREVIOUS_INSIDER_DATE_3": "",
        "MONTHLY_INCOME": "",
        "YEARLY_INCOME": "",
        "SELLER": "PROLOGIS/SECURITY CAPITAL IN",
        "S_STREET_NAME": "AIRPORT WAY",
        "S_CITY": "DENVER",
        "S_STATE": "CO",
        "BROKER": "COLLIERS",
        "BROKER_PHONE": "(404) 888-",
        "PERMANENT_LOAN": "1364500",
        "LENDER": "IBERIABANK",
        "L_STREET_NUMBER": "3625",
        "L_CITY": "ATLANTA",
        "L_PHONE": "(678) 631-",
        "CONSTRUCTION_LOAN": "",
        "C_LENDER": "",
        "C_L_STREET_NUMBER": "",
        "C_L_CITY": "",
        "C_L_PHONE": "",
        "C_L_REP": "",
        "LEASING_REP": "DRU GHEGAN",
        "EQUITY": "1312565",
        "PERCENTAGE_EQUITY": "",
        "DOWNPAYMENT": "1312565",
        "PERCENTAGE_DOWNPAYMENT": "",
        "UNDERLYING": "",
        "PURCHASE_NOTE": "",
        "ASKING_PRICE": "",
        "DESCRIPTION": "INDUSTRIAL BLDG SALE",
        "AKA": "",
        "SURVEY": "",
        "RECID": "",
        "INSIDER_SORT": "",
        "insider_date": "2016-09-30",
        "LEASING_PHONE": "(404) 349-",
        "O_STREET_NUMBER": "6105",
        "O_STATE": "GA",
        "O_ZIP": "30336",
        "LEASING_STREET_NUMBER": "6105",
        "LEASING_STREET_NAME": "PURDUE DR",
        "LEASING_CITY": "ATLANTA",
        "LEASING_ZIP": "30336",
        "LEASING_SUITE_NUMBER": "",
        "O_SUITE_NUMBER": "",
        "LEASING_STATE": "GA",
        "P_STATE": "GA",
        "OCCUPIED": "",
        "VACANT": "",
        "LOW_RENT": "",
        "START": "",
        "LEASED_PREVIOUS_90_DAYS": "",
        "M1": "COLLERS(SCOTT PLOMGREN,PRICE WEAVER,SEAN BOSWELL)",
        "M2": "BROKERED 9/16/16,PROLOGIS TO BONDED INDUS P",
        "M3": "105,600 SF,BLT 1985; 4.976 ACS;NO INFO:OCCUP,CAP;",
        "M4": "PRICE:$2.677MIL($25/SF);$1.32MIL EQ+LN:$1.37MIL,1",
        "M5": "LENDER:IBERIABANK;DDBK56662,PG451; NO PAST SALES",
        "HIGH_RENT": "",
        "LEASING_P_O_BOX_NUMBER": "",
        "O_P_O_BOX_NUMBER": "",
        "M6": "SHOW IN THE RECORDS; FULTON ASSESSORS ESTIM 2016",
        "M7": "VALUE:$2.633MIL($25/SF).",
        "2ND_94": "",
        "AFTER_3_YEARS": "",
        "MARKET_AREA": "4",
        "LEASING_REP2": "",
        "O_REP2": "",
        "ANCHOR1": "UNKNOWN TO US",
        "ANCHOR2": "",
        "B_STREET_NUMBER": "1230",
        "B_P_O_BOX_NUMBER": "",
        "B_REP2": "PRICE WEAV",
        "B_REP": "SCOTT PLOM",
        "S_STREET_NUMBER": "4545",
        "S_P_O_BOX_NUMBER": "",
        "S_ZIP": "80239",
        "S_PHONE": "(303) 375-9292",
        "S_REP2": "MICHAEL BLAIR;AN",
        "L_REP": "SETH T GRA",
        "L_REP2": "",
        "L_P_O_BOX_NUMBER": "",
        "L_STREET_NAME": "CUMBERLAND",
        "L_STATE": "GA",
        "L_ZIP": "30339",
        "C_L_REP2": "",
        "C_L_STREET_NAME": "",
        "C_L_P_O_BOX_NUMBER": "",
        "C_L_STATE": "",
        "C_L_ZIP": "",
        "S_REP": "MEGAN ROBERT,ETAL",
        "S_SUITE_NUMBER": "PROLOGIS C",
        "B_SUITE_NUMBER": "#800",
        "B_STATE": "GA",
        "B_ZIP": "30309",
        "L_SUITE_NUMBER": "BLDG2",
        "#_ACRES": 5,
        "#_SQ_FT_BUILT": "105000.0",
        "PREVIOUS_OCCUPIED": "",
        "PREVIOUS_VACANT": "",
        "UNBUILT_PHASE_2_SF": "",
        "PHASE_3_SF": "",
        "DISTRICT": "9C",
        "LANDLOT2": "",
        "PARCEL2": "",
        "PREVIOUS_SQ_FT_BUILT": "",
        "SECTION": "",
        "2ND_OWNER_PHONE": "(404) 349-6685",
        "LEASING_PHONE2_FAX": "(404) 340-",
        "LANDLOT": "69",
        "CLASSIFICATION": "",
        "C_L_SUITE_NUMBER": "",
        "#_OF_BUILDINGS": "",
        "2ND_OWNER": "BONDED INDUSTRIAL PROPS",
        "CLASSIFICATION2": "",
        "CLASSIFICATION3": "",
        "LOAN_PER_SQ_FT": "12.9952381",
        "C_LOAN_PER_SQ_FT": "",
        "1ST_92": "",
        "OCCTEST": "",
        "foreclosure_date": '2017-01-01',
        "ASSUMED_LOAN": "",
        "O_PHONE2_FAX": "(404) 349-1466",
        "M8": "",
        "M9": "",
        "M10": "",
        "2ND_92": "",
        "PHASE_4_SF": "",
        "MEDIAN_RENTAL_RATE": "",
        "LEASE_TERMS": "",
        "LOAN_START_DATE": "9/16/16",
        "LOAN_COMPLETE_DATE": "9/16/26",
        "LOAN_TERMS": "",
        "C_LOAN_START_DATE": "",
        "C_LOAN_COMPLETE_DATE": "",
        "C_LOAN_TERMS": "",
        "OWNER": "BONDED INDUSTRIAL PROPERTIES/BON",
        "LEASING_COMPANY": "BONDED IND",
        "LEASE_TERMS_ALLOWANCE": "",
        "2ND_OWNER_REP": "DRU GHEGAN,ETAL",
        "2ND_OWNER_REP2": "",
        "2ND_OWNER_STREET_NUMBER": "1805",
        "2ND_OWNER_P_O_BOX_NUMBER": "",
        "2ND_OWNER_STREET_NAME": "WESTGATE PWY",
        "2ND_OWNER_SUITE_NUMBER": "",
        "2ND_OWNER_CITY": "ATLANTA",
        "2ND_OWNER_STATE": "GA",
        "2ND_OWNER_ZIP": "30336",
        "2ND_OWNER_PHONE2_FAX": "(404) 349-",
        "PERCENTAGE_OCCUPANCY": "",
        "PERCENTAGE_VACANCY": "",
        "MANAGEMENT_COMPANY": "BONDED IND",
        "MANAGEMENT_REP": "DR8 GHEGAN",
        "MANAGEMENT_REP2": "",
        "MANAGEMENT_STREET_NUMBER": "6105",
        "MANAGEMENT_P_O_BOX_NUMBER": "",
        "MANAGEMENT_STREET_NAME": "PURDUE DRI",
        "MANAGEMENT_SUITE_NUMBER": "",
        "MANAGEMENT_CITY": "ATLANTA",
        "MANAGEMENT_STATE": "GA",
        "MANAGEMENT_ZIP": "30336",
        "MANAGEMENT_PHONE": "(404) 349-",
        "MANAGEMENT_PHONE2_FAX": "(404) 349-",
        "ATTENTION": "CONNOR DRUR",
        "built_complete": "1985-12-31",
        "ORIGINALLY_BUILT": "",
        "ATTENTION2": "DRU GHEGAN,ETAL",
        "S_PHONE2_FAX": "(770)246-6",
        "B_PHONE2_FAX": "",
        "L_PHONE2_FAX": "(678) 240-",
        "C_L_PHONE2_FAX": "",
        "1ST_96": "",
        "UNITS": nil,
        "RESULTS": "",
        "INSIDER_DESCRIPTION": "INDUSTRIAL BLDG SALE",
        "PURCHASE_NOTE_START_DATE": "",
        "PURCHASE_NOTE_DUE_DATE": "",
        "CAP_RATE": "",
        "GROSS_NET": "",
        "2ND_96": "",
        "FLOORS": "",
        "1ST_97": "",
        "FORECLOSED_PRICE": "",
        "ATTORNEY": "CARL FRANZMAN",
        "ATTORNEY_PHONE": "(404) 255-2503",
        "EXISTING_PERMANENT_LOAN": "",
        "EXISTING_CONSTRUCITON_LOAN": ""
      }
    end
  end

  factory :industrial2, class: Industrial do
    before(:create) do |industrial|
      industrial.attributes = {
        "id": 2,
        "P_NAME": "1FULTON IND BLV#5060",
        "PROJECT_TYPE": "I",
        "P_STREET_NUMBER": "5",
        "P_STREET_NAME": "FULTON INDUS BLVD",
        "P_CROSS_STREET_NAME": "SELIG DR",
        "P_CITY": "ATLANTA",
        "P_ZIP": "30336",
        "COUNTY": "FULTON (SOUTH)",
        "DISTRICT2": "",
        "SQUARE": "LL",
        "PARCEL": "077-4",
        "ZONING": "",
        "ZONING_PERMITTING_DATE": "",
        "SF_LAND": nil,
        "land_sale_date": '2017-01-01',
        "LAND_SALE_PRICE": 0,
        "PRICE_PER_ACRE": "",
        "PRICE_PER_SF_LAND": "",
        "sale_date": "2010-08-03",
        "SALE_PRICE": 700000,
        "PRICE_PER_SF_BUILDING": "34.3794509",
        "TAX_OWNER": "PIRRUNG LLC/ATLANTA BEVERAGE CO",
        "O_STREET_NAME": "FULTON INDUS",
        "O_CITY": "ATLANTA",
        "O_PHONE": "(404) 694-6700",
        "O_REP": "MARK PIRRUN",
        "BUILDER": "",
        "B_PHONE": "",
        "B_STREET_NAME": "",
        "B_CITY": "",
        "ARCHITECT": "",
        "PLANNER": "",
        "PREVIOUS_INSIDER_DATE_1": "",
        "PREVIOUS_INSIDER_DATE_2": "",
        "PREVIOUS_INSIDER_DATE_3": "",
        "MONTHLY_INCOME": "",
        "YEARLY_INCOME": "",
        "SELLER": "GARY \u0026 GLORIA LASHLEY",
        "S_STREET_NAME": "SILVER RIDGE DR",
        "S_CITY": "STONE MT",
        "S_STATE": "GA",
        "BROKER": "UNKNOWN TO US",
        "BROKER_PHONE": "",
        "PERMANENT_LOAN": "",
        "LENDER": "",
        "L_STREET_NUMBER": "",
        "L_CITY": "",
        "L_PHONE": "",
        "CONSTRUCTION_LOAN": "",
        "C_LENDER": "",
        "C_L_STREET_NUMBER": "",
        "C_L_CITY": "",
        "C_L_PHONE": "",
        "C_L_REP": "",
        "LEASING_REP": "",
        "EQUITY": "0",
        "PERCENTAGE_EQUITY": "",
        "DOWNPAYMENT": "0",
        "PERCENTAGE_DOWNPAYMENT": "",
        "UNDERLYING": "",
        "PURCHASE_NOTE": "",
        "ASKING_PRICE": "",
        "DESCRIPTION": "OFFICE-WAREHOUSE SAL",
        "AKA": "",
        "SURVEY": "",
        "RECID": "",
        "INSIDER_SORT": "",
        "insider_date": "2010-08-20",
        "LEASING_PHONE": "",
        "O_STREET_NUMBER": "5000",
        "O_STATE": "GA",
        "O_ZIP": "30336",
        "LEASING_STREET_NUMBER": "",
        "LEASING_STREET_NAME": "",
        "LEASING_CITY": "",
        "LEASING_ZIP": "",
        "LEASING_SUITE_NUMBER": "",
        "O_SUITE_NUMBER": "",
        "LEASING_STATE": "",
        "P_STATE": "GA",
        "OCCUPIED": "",
        "VACANT": "",
        "LOW_RENT": "",
        "START": "",
        "LEASED_PREVIOUS_90_DAYS": "",
        "M1": "8/3/10 SALE,LASHLEY TRACTOR SALES TO ATLANTA",
        "M2": "BEVERAGE(1 OF 2*SALES);BROKER:UNKNOWN TO US",
        "M3": "20,361 SF,BLT 1970; 2.55 ACS;USER;EXPANSION;",
        "M4": "PRICE:$700,000($34/SF),CASH;NO LOAN SHOWS YET.",
        "M5": "LENDER:NONE SHOWS YET.DEEDBK49248,PGS628,629;",
        "HIGH_RENT": "",
        "LEASING_P_O_BOX_NUMBER": "",
        "O_P_O_BOX_NUMBER": "",
        "M6": "*WAS 1 OF 2 ATLANTA BEVERAGE BOUGHT THIS DAY;",
        "M7": "THE OTHER WAS 1.39 ACS THAT SOLD TO THEM FROM",
        "2ND_94": "",
        "AFTER_3_YEARS": "",
        "MARKET_AREA": "4",
        "LEASING_REP2": "",
        "O_REP2": "",
        "ANCHOR1": "ATLANTA BEVERAGE CO",
        "ANCHOR2": "WAS LASHLEY TRACT",
        "B_STREET_NUMBER": "",
        "B_P_O_BOX_NUMBER": "",
        "B_REP2": "",
        "B_REP": "",
        "S_STREET_NUMBER": "5683",
        "S_P_O_BOX_NUMBER": "",
        "S_ZIP": "30087",
        "S_PHONE": "(404) 835-3320",
        "S_REP2": "GLORIA LASHLEY,E",
        "L_REP": "",
        "L_REP2": "",
        "L_P_O_BOX_NUMBER": "",
        "L_STREET_NAME": "",
        "L_STATE": "",
        "L_ZIP": "",
        "C_L_REP2": "",
        "C_L_STREET_NAME": "",
        "C_L_P_O_BOX_NUMBER": "",
        "C_L_STATE": "",
        "C_L_ZIP": "",
        "S_REP": "GARY LASHLEY,ETAL",
        "S_SUITE_NUMBER": "",
        "B_SUITE_NUMBER": "",
        "B_STATE": "",
        "B_ZIP": "",
        "L_SUITE_NUMBER": "",
        "#_ACRES": 3,
        "#_SQ_FT_BUILT": "20361.0",
        "PREVIOUS_OCCUPIED": "",
        "PREVIOUS_VACANT": "",
        "UNBUILT_PHASE_2_SF": "",
        "PHASE_3_SF": "",
        "DISTRICT": "14F",
        "LANDLOT2": "",
        "PARCEL2": "",
        "PREVIOUS_SQ_FT_BUILT": "",
        "SECTION": "",
        "2ND_OWNER_PHONE": "",
        "LEASING_PHONE2_FAX": "",
        "LANDLOT": "83",
        "CLASSIFICATION": "",
        "C_L_SUITE_NUMBER": "",
        "#_OF_BUILDINGS": "",
        "2ND_OWNER": "",
        "CLASSIFICATION2": "",
        "CLASSIFICATION3": "",
        "LOAN_PER_SQ_FT": "",
        "C_LOAN_PER_SQ_FT": "",
        "1ST_92": "",
        "OCCTEST": "",
        "foreclosure_date": '2017-01-01',
        "ASSUMED_LOAN": "",
        "O_PHONE2_FAX": "",
        "M8": "ROBERT ",
        "M9": "($125,000 ",
        "M10": "BEVERAGE W",
        "2ND_92": "",
        "PHASE_4_SF": "",
        "MEDIAN_RENTAL_RATE": "",
        "LEASE_TERMS": "",
        "LOAN_START_DATE": "",
        "LOAN_COMPLETE_DATE": "",
        "LOAN_TERMS": "",
        "C_LOAN_START_DATE": "",
        "C_LOAN_COMPLETE_DATE": "",
        "C_LOAN_TERMS": "",
        "OWNER": "ATLANTA BEVERAGE CO",
        "LEASING_COMPANY": "",
        "LEASE_TERMS_ALLOWANCE": "",
        "2ND_OWNER_REP": "",
        "2ND_OWNER_REP2": "",
        "2ND_OWNER_STREET_NUMBER": "",
        "2ND_OWNER_P_O_BOX_NUMBER": "",
        "2ND_OWNER_STREET_NAME": "",
        "2ND_OWNER_SUITE_NUMBER": "",
        "2ND_OWNER_CITY": "",
        "2ND_OWNER_STATE": "",
        "2ND_OWNER_ZIP": "",
        "2ND_OWNER_PHONE2_FAX": "",
        "PERCENTAGE_OCCUPANCY": "",
        "PERCENTAGE_VACANCY": "",
        "MANAGEMENT_COMPANY": "",
        "MANAGEMENT_REP": "",
        "MANAGEMENT_REP2": "",
        "MANAGEMENT_STREET_NUMBER": "",
        "MANAGEMENT_P_O_BOX_NUMBER": "",
        "MANAGEMENT_STREET_NAME": "",
        "MANAGEMENT_SUITE_NUMBER": "",
        "MANAGEMENT_CITY": "",
        "MANAGEMENT_STATE": "",
        "MANAGEMENT_ZIP": "",
        "MANAGEMENT_PHONE": "",
        "MANAGEMENT_PHONE2_FAX": "",
        "ATTENTION": "C MARK PIRR",
        "built_complete": "1970-06-15",
        "ORIGINALLY_BUILT": "",
        "ATTENTION2": "",
        "S_PHONE2_FAX": "(678) 325-",
        "B_PHONE2_FAX": "",
        "L_PHONE2_FAX": "",
        "C_L_PHONE2_FAX": "",
        "1ST_96": "",
        "UNITS": nil,
        "RESULTS": "",
        "INSIDER_DESCRIPTION": "OFFICE-WAREHOUSE SAL",
        "PURCHASE_NOTE_START_DATE": "",
        "PURCHASE_NOTE_DUE_DATE": "",
        "CAP_RATE": "",
        "GROSS_NET": "",
        "2ND_96": "",
        "FLOORS": "",
        "1ST_97": "",
        "FORECLOSED_PRICE": "",
        "ATTORNEY": "",
        "ATTORNEY_PHONE": "",
        "EXISTING_PERMANENT_LOAN": "",
        "EXISTING_CONSTRUCITON_LOAN": ""
      }
    end
  end

end
